@ECHO OFF
SET DEBUG="True"
SET STARTUP_SIGNUP_TABLE="gsg-signup-table"
SET AWS_REGION="eu-west-1"
SET AWS_ACCESS_KEY_ID="<YOUR-ACCESS-KEY-ID>"
SET AWS_SECRET_ACCESS_KEY="<YOUR-SECRET-ACCESS-KEY>"
ECHO %DEBUG%, %STARTUP_SIGNUP_TABLE%, %AWS_REGION%, %AWS_ACCESS_KEY_ID%, %AWS_SECRET_ACCESS_KEY%
